# docker-compose.yml
services:
  web:
    image: ghcr.io/${GITHUB_REPOSITORY}-backend:staging
    ports:
      - "8080:8080"
    depends_on:
      - #mariadb
      - postgres  
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ConnectionStrings__DefaultConnection: Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      AppOptions__DbConnectionString: Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      AppOptions__JwtSecret: ${JWT_SECRET}
  
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY}-frontend:staging
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf
  
  #mariadb:
   # image: mariadb:latest
  #  environment:
  #    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
 #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #    MYSQL_USER: ${MYSQL_USER}
 #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #  volumes:
  #    - mariadb_data:/var/lib/mysql
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  flyway:
    image: flyway/flyway:latest
    depends_on:
      #- mariadb
      - postgres
    environment:
      #FLYWAY_URL: jdbc:mariadb://mariadb:3306/${MYSQL_DATABASE}
      FLYWAY_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      #FLYWAY_USER: ${MYSQL_USER}
      FLYWAY_USER: ${POSTGRES_USER}
      #FLYWAY_PASSWORD: ${MYSQL_PASSWORD}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
      FLYWAY_CONNECT_RETRIES: 5
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ./server/infrastructure.Postgres/Migrations:/flyway/sql
    command: migrate

volumes:
  #mariadb_data:
  postgres_data: