# docker-compose.yml
services:
  web:
    image: ghcr.io/${GITHUB_REPOSITORY}-backend:staging
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ConnectionStrings__DefaultConnection: Server=mariadb;Database=${MYSQL_DATABASE};User=${MYSQL_USER};Password=${MYSQL_PASSWORD};
      AppOptions__JwtSecret: ${JWT_SECRET}
  
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY}-frontend:staging
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf
  
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
  
  flyway:
    image: flyway/flyway:latest
    depends_on:
      - mariadb
    environment:
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/${MYSQL_DATABASE}
      FLYWAY_USER: ${MYSQL_USER}
      FLYWAY_PASSWORD: ${MYSQL_PASSWORD}
      FLYWAY_CONNECT_RETRIES: 5
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ./server/infrastructure.Postgres/Migrations:/flyway/sql
    command: migrate

volumes:
  mariadb_data: